
package com.company.vaadinpushexample.ui;

import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;


@Route("second-window")
public class SecondWindow extends VerticalLayout
{

	/**
	 *
	 */
	public SecondWindow()
	{
		super();
		this.initUI();
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.label = new Label();

		this.label.setText("Seite 2");

		this.label.setSizeUndefined();
		this.add(this.label);
		this.setSizeFull();
	} // </generated-code>
	
	// <generated-code name="variables">
	private Label label;
	// </generated-code>
	
}
